# AirGradient Open Air Outdoor Monitor with CO2 and TVOC
# Model: O-1PST
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-open-air-o-1pst"
  friendly_name: "AG Open Air O-1PST"
  config_version: 2.0.0
  name_add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

dashboard_import:
  package_import_url: github://airgradienthq/esphome/airgradient-open-air-o-1pst.yaml
  import_full_config: false

packages:
  board: github://airgradienthq/esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5: github://airgradienthq/esphome/packages/sensor_pms5003t.yaml
  co2: github://airgradienthq/esphome/packages/sensor_s8.yaml
  tvoc: github://airgradienthq/esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://airgradienthq/esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://airgradienthq/esphome/packages/watchdog.yaml
  wifi: github://airgradienthq/esphome/packages/sensor_wifi.yaml
  mac_address: github://airgradienthq/esphome/packages/sensor_mac_address.yaml
  uptime: github://airgradienthq/esphome/packages/sensor_uptime.yaml
  safe_mode: github://airgradienthq/esphome/packages/switch_safe_mode.yaml
