# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-one"
  friendly_name: "AirGradient ONE"
  config_version: 2.0.0
  name_add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

dashboard_import:
  package_import_url: github://airgradienthq/esphome/airgradient-one.yaml
  import_full_config: false

packages:
  board:
    url: github://airgradienthq/esphome/packages/airgradient_esp32-c3_board.yaml
    refresh: 0s
  pm_2.5: github://airgradienthq/esphome/packages/sensor_pms5003.yaml
  co2: github://airgradienthq/esphome/packages/sensor_s8.yaml
  temp_humidity: github://airgradienthq/esphome/packages/sensor_sht40.yaml
  tvoc: github://airgradienthq/esphome/packages/sensor_sgp41.yaml
  display: github://airgradienthq/esphome/packages/display_sh1106_multi_page.yaml
  led: github://airgradienthq/esphome/packages/led.yaml
  led_co2: github://airgradienthq/esphome/packages/led_co2.yaml
  airgradient_api: github://airgradienthq/esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://airgradienthq/esphome/packages/watchdog.yaml
  config_button: github://airgradienthq/esphome/packages/config_button.yaml
  wifi: github://airgradienthq/esphome/packages/sensor_wifi.yaml
  mac_address: github://airgradienthq/esphome/packages/sensor_mac_address.yaml
  uptime: github://airgradienthq/esphome/packages/sensor_uptime.yaml
  safe_mode: github://airgradienthq/esphome/packages/switch_safe_mode.yaml

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
